[package]
name = "bit-match"
version = "0.4.2"
authors = ["Michael Chesser"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.18"
syn = { version = "1.0.33", features = ["extra-traits", "full"] }
quote = "1.0.7"

[features]
internal-debug = []
