[package]
name = "bit-match"
version = "0.3.0"
authors = ["Michael Chesser"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.8"
syn = { version = "1.0.13", features = ["extra-traits", "full"] }
quote = "1.0.2"

[features]
internal-debug = []