[package]
name = "bit-match"
version = "0.1.0"
authors = ["Michael Chesser"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.6"
syn = { version = "1.0.11", features = ["extra-traits", "full"] }
quote = "1.0.2"
